# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# workspace wide tests
name: rust

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

# trigger for all PRs and changes to main
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  # Run cargo fmt for all crates
  lint:
    name: Lint (cargo fmt)
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup rustfmt
        run: rustup component add rustfmt
      - name: Format object_store
        run: cargo fmt --all -- --check

  msrv:
    name: Verify MSRV (Minimum Supported Rust Version)
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-msrv
        run: cargo install cargo-msrv
      - name: Downgrade object_store dependencies
        # Necessary because tokio 1.30.0 updates MSRV to 1.63
        # and url 2.5.1, updates to 1.67
        run: |
          cargo update -p tokio --precise 1.29.1
          cargo update -p url --precise 2.5.0
          cargo update -p once_cell --precise 1.20.3
      - name: Check
        run: |
          # run `cargo msrv verify` to see problems
          cargo msrv verify --output-format=json || exit 1
